---
name: CI
on: [push, pull_request]
jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install nox
      run: python -m pip install nox
    - name: Check style
      run: nox --non-interactive -s reformat -- --check
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        include:
        - os: ubuntu-latest
          python-version: "3.10"
          python-install-version: 3.10-dev
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-install-version || matrix.python-version }}
    - name: Install nox
      run: python -m pip install nox
    - name: Run pytest
      run: nox --non-interactive -s test -p ${{ matrix.python-version }}
        --error-on-missing-interpreters
    - name: Run Pyright
      run: nox --non-interactive -s type_check
      if: ${{ always() }}
